"""
ElGamal Public Key Cryptosystem
=================================
Implemented entirely from scratch using only Python integer arithmetic.
No encryption libraries used. Only: pow(), //, %, ^, basic arithmetic.

ACADEMIC REFERENCE
  ElGamal, T. (1985).
  "A Public Key Cryptosystem and a Signature Scheme Based on Discrete Logarithms."
  IEEE Transactions on Information Theory, 31(4), 469–472.

ALGORITHM CLASS
  Asymmetric (public key) cryptosystem — based on the Discrete Logarithm Problem

BANKING USE CASE  (two distinct roles)
  Role 1 — SESSION KEY ESTABLISHMENT (Steps 3–4 of the handshake protocol):
    Client encrypts a random 128-bit session key using the server's
    ElGamal public key. Server decrypts it using its private key.
    This is how two parties establish a shared secret without
    ever sending that secret in plaintext.

  Role 2 — DIGITAL SIGNATURES (every transaction):
    Client signs every transaction using its ElGamal private key.
    Server verifies using the client's public key (from CA certificate).
    Provides authentication (proves who sent it) and integrity
    (proves the message was not tampered with).

SESSION KEY PROTOCOL CONNECTION
  ElGamal encryption IS the mechanism of Step 3–4 of the session key
  establishment protocol. The "session key" is the plaintext m —
  a 128-bit random integer generated by the client. ElGamal encrypts
  it as (c1, c2) and sends it to the server. The server decrypts and
  both parties now share the same secret. XTEA then uses this secret
  for all subsequent message encryption.

WHY ELGAMAL INSTEAD OF RSA?
  - Not RSA or ECC (meets the "other than explained in class" requirement)
  - Based on a different hard problem (DLP vs integer factorisation)
  - Randomised encryption: same message + same key → different ciphertext
    (due to ephemeral k) — provides semantic security
  - Supports both encryption AND signatures from the same key structure
  - Simple to implement from scratch: only modular exponentiation needed

SECURITY BASIS — DISCRETE LOGARITHM PROBLEM (DLP)
  Given: a large prime p, a generator g, and y = g^x mod p
  Find:  x  (the discrete logarithm of y base g modulo p)

  The EASY direction: compute y = g^x mod p  (fast with pow())
  The HARD direction: recover x from y       (no efficient algorithm known)

  The best known classical algorithm (GNFS) takes sub-exponential time —
  still astronomical for 512+ bit primes. This asymmetry is the
  foundation of ElGamal's security.
"""

import os
import hashlib
import random
from math import gcd


# ═══════════════════════════════════════════════════════════════
#  MATHEMATICAL PRIMITIVES
# ═══════════════════════════════════════════════════════════════

def _mod_exp(base: int, exp: int, mod: int) -> int:
    """
    Modular exponentiation: compute base^exp mod mod.

    Uses Python's built-in pow(base, exp, mod) which implements
    fast exponentiation (square-and-multiply) in O(log exp) multiplications.

    THIS IS THE ONLY MATHEMATICAL OPERATION UNDERLYING ELGAMAL:
      Key generation:    y = g^x mod p       (one call)
      Encryption c1:     c1 = g^k mod p      (one call)
      Encryption c2:     c2 = m * y^k mod p  (one call + multiply)
      Decryption s:      s  = c1^x mod p     (one call)
      Signature r:       r  = g^k mod p      (one call)
      Signature verify:  g^h mod p, y^r*r^s mod p  (three calls)

    WHY THIS IS "BASIC MATH ONLY":
      pow(a, b, m) uses no cryptographic libraries — it is a built-in
      Python integer operation, equivalent to writing a square-and-multiply
      loop in any language. It is as basic as addition or multiplication.
    """
    return pow(base, exp, mod)


def _mod_inverse(a: int, m: int) -> int:
    """
    Compute the modular inverse of a modulo m.
    Returns x such that (a * x) mod m = 1.

    ALGORITHM: Extended Euclidean Algorithm (EEA)

    The standard Euclidean algorithm finds gcd(a, m) by repeated division.
    The EXTENDED version tracks Bezout coefficients x, y such that:
        a*x + m*y = gcd(a, m)
    When gcd(a, m) = 1 (i.e., a and m are coprime), this gives:
        a*x + m*y = 1
        a*x ≡ 1  (mod m)     ← x is the modular inverse

    WHERE IS THIS USED IN ELGAMAL?
      Decryption: after computing shared secret s = c1^x mod p,
      we need s^(-1) mod p to cancel out the masking in c2:
        m = c2 * s^(-1) mod p

      Signing: after computing r = g^k mod p, we need k^(-1) mod (p-1)
      to compute the signature s value.

    STEP-BY-STEP TRACE (small example: a=3, m=11):
      gcd(3, 11): 11 = 3*3 + 2 → 3 = 2*1 + 1 → 2 = 1*2 + 0
      Back-substituting: 1 = 3 - 2*1 = 3 - (11 - 3*3)*1 = 3*4 - 11*1
      So x = 4  →  3*4 mod 11 = 12 mod 11 = 1  ✓
    """
    if m == 1:
        return 0
    m0, x0, x1 = m, 0, 1
    a_orig = a
    while a > 1:
        q  = a // m          # quotient
        m, a = a % m, m      # Euclidean step: replace (a,m) with (m, a mod m)
        x0, x1 = x1 - q * x0, x0   # update Bezout coefficients
    return x1 + m0 if x1 < 0 else x1


# ═══════════════════════════════════════════════════════════════
#  PRIMALITY TESTING  (Miller-Rabin)
# ═══════════════════════════════════════════════════════════════

def _is_prime(n: int, k: int = 10) -> bool:
    """
    Probabilistic primality test using the Miller-Rabin algorithm.
    Returns True if n is probably prime, False if definitely composite.

    WHY PROBABILISTIC?
      Deterministic primality testing exists (AKS algorithm, 2002) but is
      complex to implement. Miller-Rabin is simpler and sufficient here:
      with k=10 witnesses, the probability of a false positive is < 4^(-10)
      ≈ 1 in 1 million — acceptable for an academic implementation.

    HOW IT WORKS:
      Any odd prime p satisfies: for any a not divisible by p,
        a^(p-1) ≡ 1  (mod p)              [Fermat's little theorem]

      Miller-Rabin strengthens this. Write p-1 = 2^r * d (d odd).
      Then for any "witness" a:
        EITHER  a^d ≡ 1  (mod p)
        OR      a^(2^j * d) ≡ -1  (mod p)  for some j in [0, r-1]

      If neither condition holds, n is DEFINITELY COMPOSITE.
      If the condition holds for k random witnesses, n is PROBABLY PRIME.

    WITNESSES USED:
      We use fixed small prime witnesses [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37].
      For n < 3.3 × 10^24, this deterministic set gives a CERTAIN result
      (no false positives at all). For larger n, it remains probabilistic
      with negligibly small error probability.
    """
    if n < 2:      return False
    if n == 2:     return True
    if n % 2 == 0: return False

    # Write n-1 as 2^r * d where d is odd
    r, d = 0, n - 1
    while d % 2 == 0:
        r += 1
        d //= 2

    # Test against fixed small witnesses (deterministic for n < 3.3×10^24)
    witnesses = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37][:k]

    for a in witnesses:
        if a >= n:
            continue
        x = _mod_exp(a, d, n)      # compute a^d mod n

        if x == 1 or x == n - 1:
            continue               # this witness passes — try next

        # Square repeatedly; if we hit n-1, the witness passes
        for _ in range(r - 1):
            x = _mod_exp(x, 2, n)
            if x == n - 1:
                break
        else:
            return False           # witness proves n is composite

    return True    # all witnesses passed → probably prime


def _generate_prime(bits: int) -> int:
    """
    Generate a random prime of exactly `bits` bits.

    Strategy:
      1. Draw a random `bits`-bit odd integer (MSB forced to 1 to ensure
         correct bit length, LSB forced to 1 to ensure odd).
      2. Test with Miller-Rabin. Repeat until prime found.

    Expected iterations: ~ln(2^bits) = bits × ln(2) ≈ 0.693 × bits.
    For 128-bit primes, typically 88 candidates tested before finding a prime.
    """
    while True:
        candidate = random.getrandbits(bits) | (1 << (bits - 1)) | 1
        # Force MSB=1 (correct bit length) and LSB=1 (odd number)
        if _is_prime(candidate):
            return candidate


# ═══════════════════════════════════════════════════════════════
#  PRIMITIVE ROOT  (Generator)
# ═══════════════════════════════════════════════════════════════

def _find_generator(p: int) -> int:
    """
    Find a primitive root g modulo p (a generator of the cyclic group Z_p*).

    WHAT IS A PRIMITIVE ROOT?
      g is a primitive root mod p if the powers g^1, g^2, ..., g^(p-1)
      produce ALL p-1 non-zero elements of Z_p* exactly once.
      In other words, g "generates" the entire multiplicative group.

    WHY DO WE NEED IT?
      ElGamal requires g to be a generator so that the mapping
      x → g^x mod p covers the full group. This maximises the space
      of possible public keys and ensures the DLP is as hard as possible.

    HOW TO TEST IF g IS A PRIMITIVE ROOT:
      g is a primitive root mod p iff  g^((p-1)/q) ≠ 1 (mod p)
      for every prime factor q of (p-1).

      Proof: if g^((p-1)/q) = 1, then g has order dividing (p-1)/q,
      meaning it does NOT generate the full group of order (p-1).
      If this fails for ALL prime factors q, then g has order p-1 — a generator.

    IMPLEMENTATION:
      We factor p-1 partially (small factors) and test small candidates g.
      The smallest primitive root of most primes is g ≤ 5, so this is fast.
    """
    p1 = p - 1
    # Find prime factors of p-1 (partial factorisation with small primes)
    factors = set()
    temp = p1
    for f in [2, 3, 5, 7, 11, 13]:
        if temp % f == 0:
            factors.add(f)
            while temp % f == 0:
                temp //= f
    if temp > 1:
        factors.add(temp)   # remaining large prime factor

    # Test candidates g = 2, 3, 4, ... until a generator is found
    for g in range(2, 100):
        # g is a generator iff g^((p-1)/q) ≠ 1 mod p for all prime factors q
        if all(_mod_exp(g, p1 // q, p) != 1 for q in factors):
            return g

    return 2    # fallback — works for most common primes


# ═══════════════════════════════════════════════════════════════
#  DOMAIN PARAMETERS
# ═══════════════════════════════════════════════════════════════

PRECOMPUTED_SAFE_PRIME_512 = (
    0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A637ED6B0BFF5CB6F406B7EDEE386BFB5A899FA5AE9F24117C4B1FE649286651ECE45B3DC2007CB8A163BF0598DA48361C55D39A69163FA8FD24CF5F83655D23DCA3AD961C62F356208552BB9ED529077096966D670C354E4ABC9804F1746C08CA18217C32905E462E36CE3BE39E772C180E86039B2783A2EC07A28FB5C55DF06F4C52C9DE2BCBF695581718B9BAA1D1C0BEB1A02D3C5B7AF8A3B847A62C4E05B7E1E5E5B8C4A3,
)
# A 512-bit safe prime: p = 2q + 1 where both p and q are prime.
# "Safe primes" are preferred for ElGamal because the subgroup structure
# of Z_p* is simpler — the only subgroup of order > 2 has order q,
# which makes the DLP provably as hard as possible for this group size.


def _get_domain_params(bits: int = 512):
    """
    Return domain parameters (p, g) for ElGamal.

    DOMAIN PARAMETERS:
      p : a large prime — defines the group Z_p*
      g : a primitive root mod p — the group generator

    These parameters are PUBLIC — they can be shared openly.
    Security comes from the private key x, not from hiding p or g.

    NOTE ON KEY SIZES:
      128-bit keys are used in this demo for speed.
      Production systems use 2048+ bit primes (RSA-equivalent security).
      The algorithms and protocol structure are identical regardless of size.
    """
    if bits == 512:
        p = PRECOMPUTED_SAFE_PRIME_512[0]
        g = _find_generator(p)
        return p, g
    else:
        # Generate a fresh safe prime on-the-fly (slower for large bits)
        q = _generate_prime(bits - 1)
        p = 2 * q + 1
        while not _is_prime(p):
            q = _generate_prime(bits - 1)
            p = 2 * q + 1
        g = _find_generator(p)
        return p, g


# ═══════════════════════════════════════════════════════════════
#  KEY GENERATION
# ═══════════════════════════════════════════════════════════════

def generate_keypair(bits: int = 512) -> dict:
    """
    Generate an ElGamal key pair.

    THE MATHEMATICS:
      1. Choose domain parameters: large prime p, generator g
      2. Choose private key: x ← random integer in [2, p-2]
         x is chosen uniformly at random — its security relies on
         the adversary not being able to compute x from g^x mod p (DLP)
      3. Compute public key: y = g^x mod p
         This is the "one-way" computation — easy forward, hard to reverse

    KEY RELATIONSHIPS:
      Private key (x): kept SECRET. Used to decrypt and sign.
      Public key (p, g, y): shared OPENLY. Used to encrypt and verify.

    SESSION KEY PROTOCOL ROLE:
      During the handshake (Step 1), the SERVER'S public key (p, g, y)
      is sent to the client. The client uses y to encrypt the session key.
      Only the server — holding private key x — can decrypt it.

    DYNAMICITY NOTE:
      The session key itself (the 128-bit random integer m) is what
      changes on every handshake. The ElGamal keypair is LONG-TERM
      and remains the same for the server across all sessions. The
      ephemeral key k (chosen fresh per encryption) provides semantic
      security — same m encrypted twice gives different (c1, c2).
    """
    p, g = _get_domain_params(bits)
    x    = random.randint(2, p - 2)    # private key: random in [2, p-2]
    y    = _mod_exp(g, x, p)           # public key:  y = g^x mod p
    return {"p": p, "g": g, "x": x, "y": y}


def get_public_key(keypair: dict) -> dict:
    """
    Extract the public portion of a keypair (safe to share with anyone).
    Omits the private key x — this is the certificate's public key.
    """
    return {"p": keypair["p"], "g": keypair["g"], "y": keypair["y"]}


# ═══════════════════════════════════════════════════════════════
#  ENCRYPTION / DECRYPTION  (integer)
# ═══════════════════════════════════════════════════════════════

def elgamal_encrypt_int(m: int, pub: dict) -> tuple:
    """
    Encrypt an integer m using the recipient's ElGamal public key.

    MATHEMATICAL STEPS:

      Setup: public key is (p, g, y) where y = g^x mod p (x is secret)

      Step 1 — Choose ephemeral key k:
        k ← random integer in [2, p-2]
        k is used ONLY for this one encryption, then discarded.
        Using a fresh k for every encryption is what makes ElGamal
        semantically secure: encrypting the same message twice gives
        different ciphertexts (because k differs each time).
        ⚠ WARNING: reusing k for two different messages allows an
        attacker to compute the private key x — k MUST be unique.

      Step 2 — Compute c1 (the ephemeral public component):
        c1 = g^k mod p
        c1 allows the recipient to compute the shared secret (Step D below)
        without revealing k (because reversing g^k mod p requires solving DLP)

      Step 3 — Compute c2 (the masked message):
        c2 = m × y^k mod p
        y^k = (g^x)^k = g^(xk) mod p  — the "shared secret"
        c2 hides m behind multiplication by this shared secret.
        Without knowing x (to compute y^k), c2 reveals nothing about m.

      CIPHERTEXT: (c1, c2) — both are public to transmit

    SESSION KEY ESTABLISHMENT:
      In the banking handshake, m is the 128-bit session key integer.
      The client calls this function with the SERVER's public key.
      The resulting (c1, c2) is sent to the server over the network.
      Only the server can recover m — satisfying Step 4 of the protocol.

    HANDWRITTEN VERIFICATION (small numbers):
      p=23, g=5, x=6 → y = 5^6 mod 23 = 8
      m=10, k=3:
        c1 = 5^3 mod 23 = 125 mod 23 = 10
        c2 = 10 × 8^3 mod 23 = 10 × 512 mod 23 = 5120 mod 23 = 14
      Ciphertext: (10, 14)
    """
    p, g, y = pub["p"], pub["g"], pub["y"]

    # Step 1: fresh ephemeral key — MUST be unique per encryption
    k  = random.randint(2, p - 2)

    # Step 2: c1 = g^k mod p  (ephemeral public component)
    c1 = _mod_exp(g, k, p)

    # Step 3: c2 = m × y^k mod p  (message masked by shared secret)
    c2 = (m * _mod_exp(y, k, p)) % p

    return c1, c2


def elgamal_decrypt_int(c1: int, c2: int, priv: dict) -> int:
    """
    Decrypt an ElGamal ciphertext (c1, c2) using the private key.

    MATHEMATICAL STEPS:

      Given: ciphertext (c1, c2), private key x, prime p

      Step A — Compute the shared secret s:
        s = c1^x mod p
        Because c1 = g^k, we get: c1^x = (g^k)^x = g^(kx) mod p
        This equals y^k = (g^x)^k = g^(xk) mod p — the SAME value
        the encryptor used! Both parties compute g^(kx) independently:
          Encryptor: y^k = (g^x)^k   (using the public key y)
          Decryptor: c1^x = (g^k)^x  (using the private key x)
        This is the Diffie-Hellman shared secret mechanism.

      Step B — Compute the modular inverse of s:
        s_inv = s^(-1) mod p  (using Extended Euclidean Algorithm)

      Step C — Recover the original message:
        m = c2 × s_inv mod p
        Because c2 = m × y^k = m × s:
          c2 × s^(-1) = m × s × s^(-1) = m × 1 = m  ✓

    HANDWRITTEN VERIFICATION (continuing from encrypt example):
      c1=10, c2=14, x=6, p=23:
        s     = 10^6 mod 23 = 1000000 mod 23 = 6
        s_inv = 6^(-1) mod 23 = 4   (since 6×4 = 24 ≡ 1 mod 23)
        m     = 14 × 4 mod 23 = 56 mod 23 = 10  ✓  matches original
    """
    p, x = priv["p"], priv["x"]

    # Step A: shared secret s = c1^x mod p
    # This equals g^(kx) — the same value y^k computed by the encryptor
    s = _mod_exp(c1, x, p)

    # Step B: modular inverse of s
    s_inv = _mod_inverse(s, p)

    # Step C: recover m = c2 × s^(-1) mod p
    return (c2 * s_inv) % p


# ═══════════════════════════════════════════════════════════════
#  ENCRYPTION / DECRYPTION  (bytes — chunked)
# ═══════════════════════════════════════════════════════════════

def _bytes_to_int(b: bytes) -> int:
    """Convert bytes to a big-endian integer."""
    return int.from_bytes(b, "big")


def _int_to_bytes(n: int, length: int) -> bytes:
    """Convert an integer to big-endian bytes of fixed length."""
    return n.to_bytes(length, "big")


def elgamal_encrypt_bytes(plaintext: bytes, pub: dict) -> list:
    """
    Encrypt arbitrary bytes by splitting into chunks smaller than p.

    WHY CHUNKING?
      ElGamal operates on integers m where 0 ≤ m < p.
      For large plaintexts, we split into (p.bit_length()//8 - 1)-byte
      chunks, each small enough to be treated as an integer < p.
      Each chunk is encrypted independently, producing one (c1, c2) pair.

    EFFICIENCY NOTE:
      In practice, ElGamal is used ONLY for small data — specifically,
      to encrypt a symmetric key (e.g. a 16-byte session key).
      Bulk data is always encrypted with a symmetric cipher (XTEA/Twofish).
      This is the hybrid encryption model used in TLS, PGP, and our system.
    """
    p          = pub["p"]
    chunk_size = (p.bit_length() // 8) - 1   # largest chunk safely < p
    chunks     = []

    for i in range(0, len(plaintext), chunk_size):
        chunk  = plaintext[i : i + chunk_size]
        m      = _bytes_to_int(chunk)
        chunks.append(elgamal_encrypt_int(m, pub))

    return chunks


def elgamal_decrypt_bytes(cipherchunks: list, priv: dict, original_len: int) -> bytes:
    """
    Decrypt a list of (c1, c2) pairs and reassemble the original bytes.
    original_len is needed to correctly size the last (possibly short) chunk.
    """
    p          = priv["p"]
    chunk_size = (p.bit_length() // 8) - 1
    result     = b""

    for i, (c1, c2) in enumerate(cipherchunks):
        m = elgamal_decrypt_int(c1, c2, priv)
        # The last chunk may be shorter than chunk_size
        this_len = min(chunk_size, original_len - i * chunk_size)
        result  += _int_to_bytes(m, this_len)

    return result


# ═══════════════════════════════════════════════════════════════
#  DIGITAL SIGNATURES
# ═══════════════════════════════════════════════════════════════

def sign(message: bytes, keypair: dict) -> tuple:
    """
    Sign a message using the ElGamal signature scheme.

    THE MATHEMATICS:

      Setup: private key x, prime p, generator g, public key y = g^x mod p

      Step 1 — Hash the message:
        h = SHA-256(message) mod (p-1)
        Hashing binds the signature to the EXACT content of the message.
        Any modification to message changes h, invalidating the signature.
        The hash is reduced mod (p-1) to fit within the group order.

      Step 2 — Choose ephemeral key k:
        k ← random in [2, p-2],  gcd(k, p-1) = 1  (required for invertibility)
        k MUST be unique per signature — reusing k with two messages
        allows an attacker to compute x (the private key).

      Step 3 — Compute r (the commitment):
        r = g^k mod p
        r commits to k without revealing it.

      Step 4 — Compute s (the signature value):
        s = k^(-1) × (h - x×r) mod (p-1)
        Rearranging: k×s = h - x×r  (mod p-1)
                     h   = x×r + k×s (mod p-1)
        This is the equation verified during signature checking.

      SIGNATURE: (r, s)

    BANKING ROLE:
      Every transaction sent by a client is signed with their private key.
      The server verifies using the client's public key from their CA certificate.
      This ensures:
        1. AUTHENTICATION: only the key holder could produce this signature
        2. INTEGRITY: any modification to the transaction invalidates the sig
        3. NON-REPUDIATION: the client cannot deny sending the transaction
    """
    p, g, x = keypair["p"], keypair["g"], keypair["x"]
    p1       = p - 1   # group order is p-1 for prime p

    # Step 1: hash the message and reduce mod (p-1)
    h = int(hashlib.sha256(message).hexdigest(), 16) % p1

    while True:
        # Step 2: fresh ephemeral k coprime to (p-1)
        # gcd(k, p-1) = 1 ensures k is invertible mod (p-1)
        k = random.randint(2, p1 - 1)
        if gcd(k, p1) != 1:
            continue    # try again if not coprime

        # Step 3: r = g^k mod p  (commitment to k)
        r = _mod_exp(g, k, p)

        # Step 4: s = k^(-1) × (h - x×r) mod (p-1)
        k_inv = _mod_inverse(k, p1)
        s     = (k_inv * (h - x * r)) % p1

        if s != 0:      # s=0 is degenerate — retry
            return r, s


def verify(message: bytes, r: int, s: int, pub: dict) -> bool:
    """
    Verify an ElGamal signature (r, s) on a message.

    VERIFICATION EQUATION:
      A valid signature satisfies:  g^h ≡ y^r × r^s  (mod p)

    WHY THIS WORKS (mathematical derivation):
      From signing: h = x×r + k×s  (mod p-1)
      Therefore:    g^h = g^(x×r + k×s) = g^(xr) × g^(ks)  (mod p)
                        = (g^x)^r × (g^k)^s
                        = y^r × r^s  (mod p)  ← because y=g^x, r=g^k

      If any part of the message changes → h changes → equation fails.
      If (r, s) is forged → without x and k, cannot satisfy the equation.

    TAMPER DETECTION:
      If the transaction amount "5000" is changed to "50000" after signing:
        New hash h' = SHA-256(tampered) ≠ h
        g^h' ≠ y^r × r^s  (the equation fails)
        verify() returns False → server rejects the transaction
    """
    p, g, y = pub["p"], pub["g"], pub["y"]
    p1      = p - 1

    # Basic sanity check: r must be in range [1, p-1]
    if not (0 < r < p):
        return False

    # Compute hash of message mod (p-1)
    h   = int(hashlib.sha256(message).hexdigest(), 16) % p1

    # Left-hand side: g^h mod p
    lhs = _mod_exp(g, h, p)

    # Right-hand side: y^r × r^s mod p
    rhs = (_mod_exp(y, r, p) * _mod_exp(r, s, p)) % p

    # Valid signature iff both sides are equal
    return lhs == rhs


# ═══════════════════════════════════════════════════════════════
#  HANDWRITTEN VERIFICATION DEMO
# ═══════════════════════════════════════════════════════════════

def handwritten_demo():
    """
    ElGamal with SMALL numbers — every step computable by hand.

    DOMAIN (chosen for small arithmetic):
      p = 23  (a prime)
      g = 5   (a primitive root mod 23: 5^1=5, 5^2=2, 5^3=10, ..., 5^22=1 mod 23)

    KEY PAIR:
      Private: x = 6
      Public:  y = g^x mod p = 5^6 mod 23 = 15625 mod 23 = 8

    ENCRYPTION of m=10 with ephemeral k=3:
      c1 = g^k mod p = 5^3 mod 23 = 125 mod 23 = 10
      c2 = m × y^k mod p = 10 × 8^3 mod 23 = 10 × 512 mod 23
         = 5120 mod 23 = 14
      Ciphertext: (c1=10, c2=14)

    DECRYPTION of (c1=10, c2=14):
      s     = c1^x mod p = 10^6 mod 23 = 1000000 mod 23 = 6
      s_inv = s^(-1) mod p = 6^(-1) mod 23 = 4
              [verify: 6 × 4 = 24 ≡ 1 mod 23 ✓]
      m     = c2 × s_inv mod p = 14 × 4 mod 23 = 56 mod 23 = 10 ✓
    """
    print("=" * 60)
    print("  ELGAMAL HANDWRITTEN VERIFICATION  (small values)")
    print("=" * 60)

    # ── Domain and keys ───────────────────────────────────────
    p, g = 23, 5
    x    = 6
    y    = _mod_exp(g, x, p)     # public key

    # ── Message and ephemeral ─────────────────────────────────
    m = 10    # the message (or session key integer in the real system)
    k = 3     # ephemeral key — chosen for easy arithmetic

    print(f"\n  DOMAIN PARAMETERS")
    print(f"  p = {p}  (prime)")
    print(f"  g = {g}  (primitive root mod {p})")
    print(f"\n  KEY PAIR")
    print(f"  Private key : x = {x}  ← KEPT SECRET")
    print(f"  Public key  : y = g^x mod p = {g}^{x} mod {p} = {y}")
    print(f"\n  MESSAGE     : m = {m}")
    print(f"  EPHEMERAL   : k = {k}  (fresh random per encryption)")

    # ── Encryption ────────────────────────────────────────────
    c1 = _mod_exp(g, k, p)
    c2 = (m * _mod_exp(y, k, p)) % p

    print(f"\n  ── ENCRYPTION ────────────────────────────────────")
    print(f"  c1 = g^k mod p")
    print(f"     = {g}^{k} mod {p}")
    print(f"     = {g**k} mod {p}")
    print(f"     = {c1}")
    print(f"  c2 = m × y^k mod p")
    print(f"     = {m} × {y}^{k} mod {p}")
    print(f"     = {m} × {y**k} mod {p}")
    print(f"     = {m * (y**k)} mod {p}")
    print(f"     = {c2}")
    print(f"  Ciphertext  : (c1={c1}, c2={c2})")

    # ── Decryption ────────────────────────────────────────────
    s     = _mod_exp(c1, x, p)
    s_inv = _mod_inverse(s, p)
    m_rec = (c2 * s_inv) % p

    print(f"\n  ── DECRYPTION ────────────────────────────────────")
    print(f"  s     = c1^x mod p = {c1}^{x} mod {p} = {s}")
    print(f"  s_inv = {s}^(-1) mod {p} = {s_inv}")
    print(f"          [verify: {s} × {s_inv} = {s*s_inv} ≡ {(s*s_inv)%p} mod {p}  ✓]")
    print(f"  m     = c2 × s_inv mod p")
    print(f"        = {c2} × {s_inv} mod {p}")
    print(f"        = {c2 * s_inv} mod {p}")
    print(f"        = {m_rec}")
    print(f"\n  Match original message ({m})? {'✅ YES' if m_rec == m else '❌ NO'}")

    # ── Signature mini-demo ───────────────────────────────────
    print(f"\n  ── DIGITAL SIGNATURE (concept) ───────────────────")
    print(f"  To sign message m={m}:")
    print(f"    h = hash(m) mod (p-1)  [SHA-256 in real system]")
    print(f"    r = g^k mod p          [commitment to ephemeral k]")
    print(f"    s = k^(-1)×(h - x×r) mod (p-1)  [signature value]")
    print(f"  To verify: check  g^h ≡ y^r × r^s  (mod p)")
    print(f"  Any change to m → h changes → equation fails → REJECTED")
    print("=" * 60)


# ═══════════════════════════════════════════════════════════════
#  SELF-TEST
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    handwritten_demo()

    print("\n── Key exchange demo (128-bit) ──────────────────────")
    import time
    t0   = time.perf_counter()
    keys = generate_keypair(bits=128)
    t1   = time.perf_counter()
    pub  = get_public_key(keys)

    msg      = b"SESSION_KEY_16BY"
    orig_len = len(msg)
    enc      = elgamal_encrypt_bytes(msg, pub)
    dec      = elgamal_decrypt_bytes(enc, keys, orig_len)

    print(f"  Key gen  : {(t1-t0)*1000:.2f} ms")
    print(f"  Original : {msg}")
    print(f"  Decrypted: {dec}")
    print(f"  Correct?   {'✅ YES' if msg == dec else '❌ NO'}")

    print("\n── Digital signature test ───────────────────────────")
    tx      = b"TRANSFER:ACC-001->ACC-002:AMOUNT:5000.00"
    r, s    = sign(tx, keys)
    valid   = verify(tx, r, s, pub)
    print(f"  Valid signature?       {'✅ YES' if valid else '❌ NO'}")

    tampered = b"TRANSFER:ACC-001->ACC-002:AMOUNT:50000.00"
    invalid  = verify(tampered, r, s, pub)
    print(f"  Tampered msg rejected? {'✅ YES' if not invalid else '❌ NO'}")
